name: gerenciador-os-api-dev

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - gerenciador-os-api-dev_pgdata_v18:/var/lib/postgresql/data
    shm_size: 256m
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

volumes:
  gerenciador-os-api-dev_pgdata_v18:
    name: gerenciador-os-api-dev-pgdata-v18
