FROM node:lts

WORKDIR /usr/src/app

# Instala ferramentas necessárias para healthchecks
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN find . -type f -name "*.sh" -exec sed -i 's/\r$//' {} +

EXPOSE 4000

ENTRYPOINT [ "sh", "./.docker/entrypoint.dev.sh" ]