-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'TECHNICIAN', 'DEPARTMENT');

-- CreateEnum
CREATE TYPE "Department" AS ENUM ('CONTROLADORIA_GERAL_DO_MUNICIPIO', 'FUNDACAO_DE_DESENVOLVIMENTO_SOCIAL_DE_BELFORD_ROXO', 'FUNDACAO_SAUDE_DE_BELFORD_ROXO', 'FUNDO_MUNICIPAL_DE_SAUDE', 'GABINETE_DO_PREFEITO', 'GABINETE_DO_VICE_PREFEITO', 'INSTITUTO_DE_PREVIDENCIA_DOS_SERVIDORES_DE_BELFORD_ROXO', 'PROCURADORIA_GERAL_DO_MUNICIPIO', 'SECRETARIA_DE_COMBATE_A_FOME', 'SECRETARIA_MUNICIPAL_DA_CASA_CIVIL', 'SECRETARIA_MUNICIPAL_DA_MULHER', 'SECRETARIA_MUNICIPAL_DE_ACAO_COMUNITARIA', 'SECRETARIA_MUNICIPAL_DE_ADMINISTRACAO', 'SECRETARIA_MUNICIPAL_DE_AGRICULTURA', 'SECRETARIA_MUNICIPAL_DE_ASSISTENCIA_SOCIAL_E_CIDADANIA', 'SECRETARIA_MUNICIPAL_DE_CIENCIA_TECNOLOGIA_E_INOVACAO', 'SECRETARIA_MUNICIPAL_DE_COMUNICACAO_SOCIAL', 'SECRETARIA_MUNICIPAL_DE_CONSERVACAO', 'SECRETARIA_MUNICIPAL_DE_CULTURA', 'SECRETARIA_MUNICIPAL_DE_DEFESA_CIVIL', 'SECRETARIA_MUNICIPAL_DE_EDUCACAO', 'SECRETARIA_MUNICIPAL_DE_ESPORTE_E_LAZER', 'SECRETARIA_MUNICIPAL_DE_FAZENDA', 'SECRETARIA_MUNICIPAL_DE_GOVERNO', 'SECRETARIA_MUNICIPAL_DE_HABITACAO_E_URBANISMO', 'SECRETARIA_MUNICIPAL_DE_INDUSTRIA_E_COMERCIO', 'SECRETARIA_MUNICIPAL_DE_LICITACOES_E_COMPRAS', 'SECRETARIA_MUNICIPAL_DE_MEIO_AMBIENTE_E_SUSTENTABILIDADE', 'SECRETARIA_MUNICIPAL_DE_OBRAS_INFRAESTRUTURA_E_SANEAMENTO', 'SECRETARIA_MUNICIPAL_DE_ORDEM_PUBLICA', 'SECRETARIA_MUNICIPAL_DE_PROTECAO_E_DEFESA_DOS_ANIMAIS', 'SECRETARIA_MUNICIPAL_DE_SAUDE', 'SECRETARIA_MUNICIPAL_DE_SEGURANCA_PUBLICA', 'SECRETARIA_MUNICIPAL_DE_SERVICOS_PUBLICOS', 'SECRETARIA_MUNICIPAL_DE_TRABALHO_RENDA_E_ECONOMIA_SOLIDARIA', 'SECRETARIA_MUNICIPAL_DE_TRANSPORTES_E_MOBILIDADE_URBANA', 'SECRETARIA_MUNICIPAL_DE_TURISMO_E_EVENTOS', 'SECRETARIA_MUNICIPAL_DO_IDOSO', 'SECRETARIA_MUNICIPAL_ESPECIAL_DO_CHEFE_DE_GABINETE');

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "tax_identifier" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" "Role" NOT NULL,
    "department" "Department" NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_first_access" BOOLEAN NOT NULL DEFAULT true,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_tax_identifier_key" ON "users"("tax_identifier");
